[tool.poetry]
name = "mapproxy"
version = "4.0.2-post"
description = "MapProxy is an open source proxy for geospatial data."
authors = []

[tool.poetry.dependencies]
python = ">=3.12,<3.13"
PyYAML = "^6.0.2"
pyproj = "^3"
jsonschema = "^4"
werkzeug = "^3"
future = "^1.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
